services:
  pong-frontend:
    build:
      context: ./pong-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./pong-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - transcedence-network

  userx:
    build:
      context: ./pong-frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./pong-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - transcedence-network

  usery:
    build:
      context: ./pong-frontend
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    volumes:
      - ./pong-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - transcedence-network

  pong-backend:
    build:
      context: ./pong-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pong-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - transcedence-network

volumes:
  node_modules:

networks:
  transcedence-network:
    driver: bridge