services:
  pong-frontend:
    build:
      context: ./pong-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./pong-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - transcedence-network

  pong-backend:
    build:
      context: ./pong-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pong-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ADRESS=192.0.7
      - RPC_URL=http://blockchain:8545
    command: npm run dev
    networks:
      - transcedence-network

  blockchain:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    container_name: hardhat-node
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/app
      - /app/node_modules
    command: ./hardhat-entrypoint.sh
    networks:
      - transcedence-network

volumes:
  node_modules:

networks:
  transcedence-network:
    driver: bridge